### ISSUE TITLE
Implement argument parser

### ISSUE THREAD

**Issue by thiagolrpinho** [rafaelcn/jvm#3]
To initialize the virtual machine we have to have an argument parser. That is, an entry algorithm which parses the flag sent to the _njvm_ and initialize it properly.

**Comment by thiagolrpinho** [comment]
Done!

**Comment by thiagolrpinho** [comment]
Done. Main not compiling thought, need to fix vm_init

**Comment by rafaelcn** [comment]
Don't close an issue until you propose a PR as this issue will be closed after the issue is merged.

**Comment by rafaelcn** [comment]
This process is done automatically, so don't worry about it. Propose a PR, I will review it and then, after its closure, it will be merged and this issue will be closed.
